### ISSUE TITLE
Can we play RTMP ?

### ISSUE THREAD

**Issue by satyamub** [jgh-/VideoCore#272]
Do we have any component in Videocore where we can play the RTMP url?

**Comment by JALsnipe** [comment]
Duplicate of #36.

**Comment by chinnuios** [comment]
@JALsnipe  dispute yet am not solving that issue (videocore 0.1.12). now am using videocore 0.3.2 still am  having same issue . RTMP session does not created " create stream". it is stopped at client state:7 
track command: release stream 
then state goes to 11 , disconnected
what is reason behind the issue ? 
please help me out this issue.

Thank you

**Comment by satyamub** [comment]
@chinnuios  did i send you the changed file content in video core library in email?

**Comment by chinnuios** [comment]
@satyamub   Hi, No you didn't send any file.please send to ioschinnu@gmail.com.  is that work with Red5 server or not.PLEASE MENTION what you have changed in that.

**Comment by satyamub** [comment]
No it seems, it does not work with Red5 server. I checked with Red5 1.4. You can check. I am sending you a file, you need to replace that in the library. Sending you the email.

**Comment by chinnuios** [comment]
@satyamub  Hi, thanks for replay you are saying that it is not working with the red5 then what is the need of changing that file. any ways i will try.

**Comment by chinnuios** [comment]
@satyamub , I had been attached your file but i getting same error. In RTMP session.cpp file into release stream. please help me out of this problem

**Comment by satyamub** [comment]
@chinnuios  is that a compilation error or when you try to stream, you get error. Please be specific. If that is compilation error send me your project files if you don't mind and I will try make that to work.

**Comment by chinnuios** [comment]
@satyamub  now i am not getting any error but it is not working with the Red5 server and vidocore 0.3.2

**Comment by satyamub** [comment]
I am sorry then .. may be its not compatible to Red5. Please downgrade the red5 server to 1.0.3 and test.. it was more stable and working I tested...

**Comment by chinnuios** [comment]
@satyamub  how can i give random stream key to rtmp url ??
i'm given this type of stream key, it's work done  and playing live stream otherwise not work.
 streamkey: @"4528585/457"    ---- Done
@"423588/7425/75225 ------ not Done

**Comment by satyamub** [comment]
@chinnuios it depends upon the server configuration....Even some cases, my server guy gives me rtmp://ip/live/username and stream name "" and it works... Please confirm from the server people... they will give you good insight!!

**Comment by chinnuios** [comment]
@satyamub  okay, thank you
